<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharpServer</RootNamespace>
    <AssemblyName>CSharpServer</AssemblyName>
    <StartupObject />
    <AssemblyTitle>CSharpServer</AssemblyTitle>
    <Product>CSharpServer</Product>
    <Copyright>Copyright ©  2022</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.22.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="NLog" Version="5.1.2" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="protobuf-net.Core" Version="3.2.56" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="NOBService.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AgentServerModule\AgentServerModule.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\DBAgentServerModule\DBAgentServerModule.csproj" />
  </ItemGroup>
</Project>