org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

systemProp.gradle.internal.http.connectionTimeout=60000
systemProp.gradle.internal.http.socketTimeout=60000
systemProp.gradle.internal.http.ssl.ignoreCertificateErrors=true